Repository pilagod/waallet-extension, pull requests merged in 2024-08, with the labels that each got.

#194 Refine env
  .env.development.example
Labels: documentation

#196 Refine document
  README.md
  demo.md
Labels: documentation

#198 Fix background middleware
  app/storage/index.ts
  app/storage/middleware/background.ts
  package-lock.json
  package.json
Labels: bug

#197 Onboarding with SimpleAccount
  app/page/account/create/index.tsx
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  app/storage/slice/account.ts
  config/development/index.ts
  packages/account/SimpleAccount/factory.ts
  packages/account/SimpleAccount/index.ts
  packages/util/address/index.ts
  storage/local/manager.ts
  storage/local/state.ts
Labels: enhancement

#199 [EIP-712] Restruct pending requests
  app/hook/storage.ts
  app/index.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/storage/slice/transaction.ts
  background/index.ts
  background/pool.ts
  storage/local/actor.ts
  storage/local/index.ts
  storage/local/state.ts
Labels: refactoring

#200 [EIP-712] Add request pool
  app/page/home/activity.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/storage/slice/transaction.ts
  background/index.ts
  background/pool.ts
  background/provider.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/pool/request/handler.ts
  packages/waallet/background/pool/request/index.ts
  packages/waallet/background/pool/request/transaction.ts
  packages/waallet/background/provider.ts
  storage/local/state.ts
Labels: refactoring

#204 Migrate storage hook
  app/index.tsx
  app/page/home/activity.tsx
  app/page/home/token.tsx
  app/page/receive/index.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/storage/index.ts
Labels: refactoring

#201 [EIP-712] Add eth_signTypedData_v4 rpc method
  background/pool.ts
  packages/account/PasskeyAccount/index.ts
  packages/account/PasskeyAccount/passkeyOwner.ts
  packages/account/PasskeyAccount/passkeyOwnerP256.test.ts
  packages/account/PasskeyAccount/passkeyOwnerP256.ts
  packages/account/PasskeyAccount/passkeyOwnerWebAuthn.ts
  packages/account/SimpleAccount/index.ts
  packages/account/index.ts
  packages/account/skeleton.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/pool/request/eip712.ts
  packages/waallet/background/pool/request/handler.ts
  packages/waallet/background/pool/request/index.ts
  packages/waallet/background/provider.ts
  packages/waallet/background/provider.v0_6.test.ts
  packages/waallet/background/provider.v0_7.test.ts
  packages/waallet/rpc.ts
Labels: enhancement

#203 [EIP-712] Handle in app
  app/component/qrCode.tsx
  app/component/scrollableWrapper.tsx
  app/hook/storage.ts
  app/index.tsx
  app/page/review/eip712.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/storage/slice/transaction.ts
  background/index.ts
  background/pool.ts
  packages/eip/712/index.ts
  packages/primitive/bytes.ts
  packages/util/byte/index.ts
  packages/util/testing/suite/account.ts
  packages/waallet/background/pool/request/eip712.ts
  packages/waallet/background/provider.v0_6.test.ts
  packages/waallet/background/provider.v0_7.test.ts
  packages/waallet/rpc.ts
  storage/local/actor.ts
  storage/local/index.ts
  storage/local/state.ts
Labels: enhancement

#206 Refine resolve request flow
  app/hook/storage.ts
  app/index.tsx
  app/page/review/eip712.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/storage/index.ts
  app/storage/slice/request.ts
  app/storage/slice/state.ts
  app/storage/slice/transaction.ts
  background/index.ts
  background/pool.ts
  storage/local/actor.ts
  storage/local/index.ts
  storage/local/state.ts
Labels: refactoring

#208 Refine address usage in app
  app/component/accountItem.tsx
  app/component/qrCode.tsx
  app/component/tokenItem.tsx
  app/hook/storage.ts
  app/page/account/create/index.tsx
  app/page/account/list/index.tsx
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  app/page/home/token.tsx
  app/page/importToken/index.tsx
  app/page/receive/index.tsx
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  app/storage/slice/account.ts
  app/storage/slice/request.ts
  background/index.ts
  packages/account/manager/index.ts
  packages/contract/erc20.ts
  packages/primitive/address.test.ts
  packages/primitive/address.ts
  packages/token/index.ts
  packages/util/address/index.ts
  packages/util/number/index.ts
  packages/waallet/background/provider.v0_6.test.ts
  storage/local/actor.ts
  storage/local/index.ts
  storage/local/manager.ts
  storage/local/state.ts
Labels: refactoring

#207 Extract create account
  app/storage/slice/account.ts
  storage/local/actor.ts
  storage/local/index.ts
  storage/local/state.ts
Labels: refactoring

#209 Refine dir
  app/index.tsx
  app/page/home/activity.tsx
  app/page/network/list/index.tsx
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  app/page/token/import/index.tsx
  app/storage/slice/request.ts
  background/index.ts
  config/development/index.ts
  config/index.ts
  config/test/index.ts
  contents/waallet.ts
  packages/eip/1193/index.ts
  packages/eip/20/contract.test.ts
  packages/eip/20/contract.ts
  packages/eip/4337/bundler/estimator.ts
  packages/eip/4337/bundler/provider.ts
  packages/eip/4337/bundler/rpc.ts
  packages/eip/4337/index.ts
  packages/eip/4337/paymaster/NullPaymaster/index.ts
  packages/eip/4337/paymaster/VerifyingPaymaster/index.ts
  packages/eip/4337/paymaster/VerifyingPaymaster/index.v0_6.test.ts
  packages/eip/4337/paymaster/VerifyingPaymaster/index.v0_7.test.ts
  packages/eip/4337/paymaster/index.ts
  packages/eip/4337/userOperation/index.ts
  packages/eip/4337/userOperation/v0_6.ts
  packages/eip/4337/userOperation/v0_7.ts
  packages/eip/6939/index.ts
  packages/network/manager/index.ts
  packages/network/manager/single.ts
  packages/util/testing/suite/account.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/pool/request/handler.ts
  packages/waallet/background/provider.ts
  packages/waallet/rpc.ts
  storage/local/actor.ts
  storage/local/manager.ts
  storage/local/state.ts
Labels: refactoring
