Repository pilagod/waallet-extension, pull requests merged in 2024-06, with the labels that each got.

#118 refac: Move token update to background
  app/page/info/index.tsx
  app/page/info/tokens.tsx
  background/index.ts
Labels: refactoring

#119 Refine storage update by patches
  app/storage/index.ts
  app/storage/messenger.ts
  app/storage/middleware/background.ts
  background/index.ts
  background/messages/storage.ts
  packages/storage/observable.test.ts
  packages/storage/observable.ts
  storage/local/index.ts
Labels: refactoring

#121 Refine account and paymaster
  app/page/authorization/userOperation.tsx
  packages/account/PasskeyAccount/index.test.ts
  packages/account/PasskeyAccount/index.ts
  packages/account/SimpleAccount/index.ts
  packages/account/index.ts
  packages/account/skeleton.ts
  packages/node/index.ts
  packages/paymaster/VerifyingPaymaster/index.test.ts
  packages/paymaster/VerifyingPaymaster/index.ts
  packages/paymaster/index.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/provider.test.ts
  packages/waallet/background/provider.ts
  storage/local/manager.ts
Labels: refactoring

#122 Refine account entry point usage
  app/page/authorization/userOperation.tsx
  packages/account/PasskeyAccount/factory.ts
  packages/account/PasskeyAccount/index.ts
  packages/account/SimpleAccount/factory.ts
  packages/account/SimpleAccount/index.ts
  packages/account/factory.ts
  packages/account/index.ts
  packages/account/skeleton.ts
  packages/bundler/provider.ts
  packages/waallet/background/provider.test.ts
  packages/waallet/background/provider.ts
  packages/waallet/rpc.ts
Labels: enhancement

#125 Refine tests
  config/test/index.ts
  packages/account/PasskeyAccount/index.test.ts
  packages/account/SimpleAccount/index.test.ts
  packages/network/manager/single.ts
  packages/paymaster/VerifyingPaymaster/index.test.ts
  packages/util/testing/suite/account.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/provider.test.ts
Labels: refactoring

#129 Upgrade plasmo
  package-lock.json
  package.json
Labels: enhancement

#127 Send token in Send page
  app/page/info/tokens.tsx
  app/page/send.tsx
  packages/network/util/index.ts
  packages/util/number/index.ts
Labels: enhancement

#128 Send token in token modal
  app/page/info/tokens.tsx
Labels: enhancement

#130 Add the link on Native token in token modal
  app/page/info/tokens.tsx
Labels: enhancement

#131 Integrate simple account 0.7
  app/component/navbar.tsx
  app/page/authorization/userOperation.tsx
  app/page/info/index.tsx
  app/storage/index.ts
  background/pool.ts
  config/development/index.ts
  config/index.ts
  config/test/index.ts
  packages/account/PasskeyAccount/index.test.ts
  packages/account/SimpleAccount/index.v0_6.test.ts
  packages/account/SimpleAccount/index.v0_7.test.ts
  packages/account/index.ts
  packages/account/skeleton.ts
  packages/bundler/index.ts
  packages/bundler/provider.ts
  packages/bundler/userOperation/index.ts
  packages/bundler/userOperation/v0_6.ts
  packages/bundler/userOperation/v0_7.ts
  packages/network/manager/single.ts
  packages/paymaster/VerifyingPaymaster/index.test.ts
  packages/paymaster/VerifyingPaymaster/index.ts
  packages/paymaster/index.ts
  packages/util/address/index.ts
  packages/util/json/index.test.ts
  packages/util/json/index.ts
  packages/util/number/index.ts
  packages/util/testing/suite/waallet.ts
  packages/waallet/background/pool/transaction/index.ts
  packages/waallet/background/pool/transaction/sender.ts
  packages/waallet/background/pool/userOperation/index.ts
  packages/waallet/background/pool/userOperation/sender.ts
  packages/waallet/background/provider.ts
  packages/waallet/background/provider.v0_6.test.ts
  packages/waallet/background/provider.v0_7.test.ts
  packages/waallet/rpc.ts
  storage/local/index.ts
  storage/local/manager.ts
  typing/index.ts
Labels: enhancement

#132 bug: Sign message with ethereum signed prefix
  app/page/authorization/userOperation.tsx
  packages/account/PasskeyAccount/passkeyOwnerP256.test.ts
  packages/account/PasskeyAccount/passkeyOwnerP256.ts
  packages/account/PasskeyAccount/passkeyOwnerWebAuthn.ts
  packages/primitive/bytes.test.ts
  packages/primitive/bytes.ts
  packages/primitive/index.ts
  packages/util/byte/index.ts
Labels: bug

#133 Verifying paymaster 0.7
  config/test/index.ts
  packages/bundler/userOperation/v0_7.ts
  packages/paymaster/VerifyingPaymaster/index.ts
  packages/paymaster/VerifyingPaymaster/index.v0_6.test.ts
  packages/paymaster/VerifyingPaymaster/index.v0_7.test.ts
  packages/paymaster/index.ts
  packages/util/testing/suite/waallet.ts
Labels: enhancement
