Repository pilagod/waallet-extension, pull requests merged in 2024-07, with the labels that each got.

#137 Support 0.7 in app
  app/component/navbar.tsx
  app/index.tsx
  app/page/authorization/transaction.tsx
  app/page/info/activity.tsx
  app/page/send.tsx
  app/path.ts
  app/storage/index.ts
  app/storage/messenger.ts
  background/index.ts
  background/pool.ts
  config/development/index.ts
  packages/bundler/userOperation/v0_6.ts
  packages/bundler/userOperation/v0_7.ts
  storage/local/index.ts
  storage/local/manager.ts
  storage/local/state.ts
Labels: enhancement

#141 Gas price estimator
  app/page/authorization/transaction.tsx
  packages/bundler/provider.ts
  packages/bundler/rpc.ts
  packages/gas/price/estimator.ts
  packages/waallet/background/pool/transaction/sender.ts
  packages/waallet/background/provider.ts
  packages/waallet/background/provider.v0_6.test.ts
  packages/waallet/background/provider.v0_7.test.ts
  packages/waallet/rpc.ts
  storage/local/index.ts
Labels: enhancement

#148 Refine CI
  .github/workflows/test.yml
Labels: enhancement

#151 Wait for userOpEstimating to finish
  app/page/authorization/transaction.tsx
Labels: enhancement

#149 Switch account & network in authorization
  app/index.tsx
  app/page/authorization/transaction.tsx
  app/storage/index.ts
Labels: enhancement

#152 Add markup for TransactionAuthorization page
  app/component/button.tsx
  app/component/divider.tsx
  app/component/stepBackHeader.tsx
  app/index.tsx
  app/page/authorization/transaction.tsx
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  assets/arrowLeft.svg
  assets/gas.svg
  assets/wallet.svg
  style.css
Labels: enhancement

#154 Split app storage into slices
  app/storage/index.ts
  app/storage/middleware/background.ts
  app/storage/slice/account.ts
  app/storage/slice/network.ts
  app/storage/slice/state.ts
  app/storage/slice/transaction.ts
Labels: refactoring

#160 Fix ci
  config/test/index.ts
Labels: bug

#157 Refactor passkey owner
  app/page/webauthn/authentication.tsx
  app/page/webauthn/devtool.tsx
  app/page/webauthn/registration.tsx
  background/messages/mCreateWindow.ts
  contents/messages.ts
  packages/account/PasskeyAccount/index.ts
  packages/account/PasskeyAccount/passkeyOwner.ts
  packages/account/PasskeyAccount/passkeyOwnerP256.test.ts
  packages/account/PasskeyAccount/passkeyOwnerP256.ts
  packages/account/PasskeyAccount/passkeyOwnerWebAuthn.ts
  packages/waallet/content/provider.ts
  packages/webAuthn/background/index.ts
  packages/webAuthn/content/index.ts
  packages/webAuthn/content/method.ts
  packages/webAuthn/index.ts
Labels: refactoring

#159 Review for sc UI
  app/index.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/path.ts
  assets/contract.svg
Labels: enhancement

#158 Add Passkey signing page and Toast
  app/component/toast.tsx
  app/context/toastContext.tsx
  app/index.tsx
  app/page/home/index.tsx
  app/page/home/token.tsx
  app/page/review/index.tsx
  app/page/review/transaction.tsx
  app/path.ts
  app/storage/slice/state.ts
  assets/contract.svg
  assets/failed.svg
  assets/passkey.svg
  assets/sent.svg
  assets/success.svg
Labels: enhancement

#164 Upgrade packages
  package-lock.json
  package.json
Labels: enhancement

#163 Extract hooks
  app/hook/storage.ts
  app/storage/index.ts
Labels: refactoring

#165 Refine context hook
  app/context/provider.tsx
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  app/page/home/token.tsx
  app/page/review/transaction.tsx
  app/page/send.tsx
Labels: refactoring

#167 Refine storage id
  app/hook/storage.ts
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  app/storage/slice/account.ts
  storage/local/index.ts
  storage/local/state.ts
Labels: enhancement

#166 Refine Send token flow
  app/component/stepBackHeader.tsx
  app/page/review/transaction.tsx
  app/page/send.tsx
  app/page/send/index.tsx
Labels: enhancement

#156 Refine Activity
  app/page/home/activity.tsx
  app/util/calldata.test.ts
  app/util/calldata.ts
  assets/arrowDownLeft.svg
  assets/arrowRightArrowLeft.svg
  assets/arrowUpRightFromSquare.svg
  assets/circleQuestion.svg
  assets/circleXmark.svg
  assets/clock.svg
  assets/octagonXmark.svg
  background/index.ts
  packages/account/PasskeyAccount/index.ts
  packages/account/SimpleAccount/index.ts
  packages/token/index.ts
Labels: refactoring

#171 Add Receive (qrcode) page
  app/component/qrCode.tsx
  app/component/toast.tsx
  app/context/toastContext.tsx
  app/index.tsx
  app/page/home/index.tsx
  app/page/receive/index.tsx
  app/path.ts
  assets/copy.svg
  package-lock.json
  package.json
  style.css
Labels: enhancement

#170 Refine Select token
  app/component/tokenItem.tsx
  app/component/tokenList.tsx
  app/context/provider.tsx
  app/index.tsx
  app/page/home/token.tsx
  app/page/send/index.tsx
  app/util/getUserTokens.ts
Labels: enhancement

#173 Refine Send amount
  app/page/send/index.tsx
Labels: enhancement

#172 Refine Select address
  app/component/accountItem.tsx
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  style.css
Labels: enhancement

#176 Add account list
  app/component/passkeyVerification.tsx
  app/index.tsx
  app/page/accountList/index.tsx
  app/page/home/navbar.tsx
  app/page/review/transaction.tsx
  app/path.ts
  assets/circleCheck.svg
  assets/plus.svg
Labels: enhancement

#177 Add network list
  app/hook/storage.ts
  app/index.tsx
  app/page/home/navbar.tsx
  app/page/networkList/index.tsx
  app/path.ts
  assets/circle.svg
  assets/circleDot.svg
  assets/ethereumLight.svg
  assets/polygon.svg
  config/network/index.ts
Labels: enhancement

#178 Add import token
  app/component/button.tsx
  app/component/input.tsx
  app/index.tsx
  app/page/home/token.tsx
  app/page/importToken/index.tsx
  app/path.ts
Labels: enhancement

#181 Add Polygon network
  config/development/index.ts
  config/network/index.ts
Labels: enhancement

#179 Propagate error to app
  app/page/review/transaction.tsx
  background/messages/JsonRpcRequest.ts
  packages/bundler/provider.ts
  packages/rpc/json/error.ts
  packages/rpc/json/provider.ts
  packages/waallet/content/provider.ts
Labels: enhancement

#183 Wrap nonce manager
  config/test/index.ts
Labels: bug

#182 Refine Home and Send page
  app/component/accountItem.tsx
  app/component/scrollableWrapper.tsx
  app/index.tsx
  app/page/accountList/index.tsx
  app/page/home/activity.tsx
  app/page/home/token.tsx
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  style.css
Labels: enhancement

#180 Add name to account
  app/index.tsx
  app/page/account/create/index.tsx
  app/page/account/list/index.tsx
  app/page/home/index.tsx
  app/page/home/navbar.tsx
  app/page/receive/index.tsx
  app/page/review/transaction.tsx
  app/path.ts
  app/storage/slice/account.ts
  assets/plus.svg
  storage/local/index.ts
  storage/local/state.ts
Labels: enhancement

#184 Refine token symbol
  app/hook/storage.ts
  app/page/account/list/index.tsx
  app/page/home/activity.tsx
  app/page/home/index.tsx
  app/page/home/token.tsx
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  app/util/getUserTokens.ts
  config/network/index.ts
Labels: enhancement

#185 Add contributors
  README.md
Labels: documentation

#186 Horizontal center app
  app/index.tsx
Labels: enhancement

#187 Close app after review confirmed when opened by DApp
  app/page/review/index.tsx
  background/index.ts
  package.json
  tabs/notification.tsx
Labels: enhancement

#189 Fix send token
  app/page/review/transaction.tsx
  app/page/send/index.tsx
  background/messages/JsonRpcRequest.ts
Labels: bug
